export const upToBig = '@media only screen and (max-width : 1100px)'
export const upToMediumBig = '@media only screen and (max-width : 767px)'
export const upToMedium = '@media only screen and (max-width : 650px)'
export const upToSmall = '@media only screen and (max-width : 515px)'

export const atLeastExtraSmall = '@media only screen and (min-width : 301px)'
export const atLeastSmall = '@media only screen and (min-width : 519px)'
export const atLeastMediumBig = '@media only screen and (min-width : 768px)'
export const atLeastBig = '@media only screen and (min-width : 1050px)'
export const atLeastHuge = '@media only screen and (min-width : 1242px)'
