export default {
  title: `The Science of People in Tech`,
  guests: [
    {
      name: 'Omoju Miller',
      twitter: 'omojumiller',
      tips: [
        `Always ask why?`,
        `Why do we get the results we have? Why is the sky blue? Never lose your curiosity`,
      ],
      picks: [
        `[Danger of a single story](https://www.ted.com/talks/chimamanda_adichie_the_danger_of_a_single_story) - TED talk`,
        `[Tomorrow Looks Bright Newsletter](http://www.tomorrowlooksbright.com/)`,
        `[Call Your Girlfriend](http://callyourgirlfriend.com/) Podcast`,
        `[Recode Decode](http://www.recode.net/recode-decode-podcast-kara-swisher)`,
      ],
    },
    {
      name: 'Steve Andrews',
      twitter: 'SteveAndrews',
      links: [
        `[Jack Ma Says Women Executives Are Alibaba’s ‘Special Sauce’](http://www.huffingtonpost.com/2015/05/20/jack-ma-alibaba-women_n_7344316.html)`,
      ],
      tips: [
        `[Platinum Bay](http://www.platinumbay.com/) is hiring`,
      ],
    },
    {
      name: 'Kate Edwards',
      twitter: 'IGDA_ED',
      links: [
        `[Google Unconscious Bias Training](https://www.youtube.com/watch?v=nLjFTHTgEVU)`,
        `[Facebook Unconscious Bias Training](https://managingbias.fb.com/)`,
        `[Microsoft Unconscious Bias Training](https://www.mslearning.microsoft.com/course/72169/launch)`,
      ],
      tips: [
        `Be aware that you - and everyone - has natural biases`,
      ],
    },
  ],
  description: `
    The JavaScript community is composed of a ton of people with a ton of different backgrounds and privilege. We need to do our very best to make everyone feel as included as possible. It makes everything better when we work to foster a welcoming and friendly community. We're going to talk about what you can do to improve your workspace and community.
  `,
  hangoutId: 'carao3pdrl3bag1kf8l9frerml4',
  youTubeId: '-rH-W483sUg',
  podbeanId: '4ajwx-5f40ab',
  shortUrl: 'http://jsair.io/science',
  host: {
    tips: [
      `Free your mind and use reminders`,
    ],
    picks: [
      `[You Can Sit With Us](https://cottonbureau.com/products/you-can-sit-with-us) T-Shirt`,
      `[Erwan Datin](https://twitter.com/erwan_datin) created a JS Air app in React Native! [Repo](https://github.com/MacKentoch/jsair-mobile), [iOS](https://itunes.apple.com/fr/app/js-air/id1112141070?mt=8), [Android](https://play.google.com/store/apps/details?id=com.jsair)`,
      `[Becoming Betazoid How to Listen and Empathize with Others in the Workplace](https://youtu.be/ypdHBfLXoHI) – [Joe Eames](https://twitter.com/josepheames)`,
    ],
  },
  panelists: [
    {
      twitter: 'drboolean',
      picks: [
        `[Algebra Ch 0](http://www.amazon.com/Algebra-Chapter-Graduate-Studies-Mathematics/dp/0821847813)`,
        `[States and Nomads - Zach Tellman](https://www.youtube.com/watch?v=KGaFcI2UNrI)`,
        `[PureScript Tropical Miniconf](http://www.meetup.com/Bay-Area-PureScript-Meetup/events/230451975/)`,
      ],
    },
    {
      twitter: 'getify',
      links: [
        `[A Speaker’s Notes](https://www.youtube.com/watch?v=IwYcVqIjbb4) talk from Fluent Conf ‘16 about making more room on the conference stage for more voices.`,
      ],
      tips: [
        `Write code as if it was intended for kids to read and learn.`,
      ],
      picks: [
        `[Simplified JS Jargon](http://jargon.js.org/)`,
        `[Minimax Algorithm](https://en.wikipedia.org/wiki/Minimax), aka how to have a computer beat/tie you at Tic-Tac-Toe`,
        `[MakerSquare](http://makersquare.com) opens new NYC campus`,
      ],
    },
  ],
  transcript: `
    KENT: Java Script Air. Hello, everyone! My name is Kent C. Dodds, and I am your host for this Java Script web platform podcast broadcast thing, that is awesome. And today we're going to be talking about the science of people in tech. Really excited to have some people on the show who are really interested in this and have a lot of experience and background on this subject.

    Before we get into that, I'd like to give a shout out to the sponsors that make some of the cool things about this podcast possible. Our premiere sponsor is Egghead.io. They have a huge library of bite sized web development training videos. Check them out for content on JavaScript, Angular, React, Node and more, including Redux. I hear that Dan Abramov is working on a big Redux series, so if that's your thing, look forward to that.

    Frontend Masters is a recorded expert-led workshop with courses on Advanced JavaScript, Asynchronous and Functional JS, as well as lots of other great courses on Frontend topics.
    And TrackJS reports bugs in your JavaScript before customers notice them, and with their telemetry timeline, you'll have the context to actually fix them. Check them out and start tracking JavaScript errors today at TrackJS.com.

    And then SparkPost is email delivery built for developers. Build something awesome with their Node JS library or SMTP relay. Start sending 100,000 emails free with SparkPost at SparkPost.com/JSAir.

    And finally, WebStorm is a powerful JavaScript IDE. It makes developers more productive with its super intelligent code assistance for JavaScript, Node JS, Angular and React, and in integration with lots of different tools. Check them out at JetBrains.com/WebStorm.

    Okay, so this is a live show, so for any of you who are watching the show live, we want to engage with you. And so, if you have any questions from our, the people on the panel or our guests, during the show, then you can tweet with the hashtag #JsAirQuestion and we will get to those questions at the end of the show.

    And then, this is a weekly live show. Next week, we're going to be talking with Lee Byron and Nick, I don't know how to say his last name, Schrock? (chuckles) From Facebook about transitioning from REST to GraphQL. It should be a solid show. Great, and then, as always, follow us on Twitter, Facebook and Google Plus to keep up with the latest from the show.
    And with that, let's go ahead and introduce who's on the show today. So for our panelists, we have Brian Lonsdorf.

    BRIAN: Hello.

    KENT: And Kyle Simpson.

    KYLE: Hello, everyone.

    KENT: And then for our guests, we have Kate Edwards.

    KATE: Hello.

    KENT: And Omoju Miller.

    OMOJU: Hello.

    KENT: And Steve Andrews.

    STEVE: Hello.

    KENT: And we're happy to have them all here today to talk about the science of people in tech. So before we get into that, let's get a quick intro to our guests, and then we can start chatting about our topic. So Kate, why don't we get an intro to you first?

    KATE: Okay, so I'm Kate Edwards. I'm the executive director of the International Game Developers Association, which is the professional society for anyone who makes video games. And I also, my background is in geography and cartography, and I've been doing what I call culturalization work in the game industry for over 20 years.

    KENT: Wow, yeah, really interested to hear about your experiences there. Very cool. Omoju?

    OMOJU: Hi everyone, my name is Omoju Miller. I just finished my PhD from Berkeley in Computer Science and education--

    KENT: Congratulations!

    OMOJU: Thank you! I have 15 years of AI background, studying how people learn, as well as making machines behave like people. I am currently the head of a board of advisors at a very interesting start-up that I'm super excited about, Learner's Guild.

    KENT: Very cool, yeah, I know that lots of us on the show regularly really care about learning and education, so that's great. Steve, why don't you go next?

    STEVE: I'm Steve Andrews, I am the founder and executive director of Platinum Bay Technologies, and we are a software company specially designed to employ technically capable autistic adults.

    KENT: That's a noble cause. Thank you for doing that, and we look forward to talking to you about what we can do practically to help people of all backgrounds. Great, so yeah, let's go ahead and get into our conversation. I think there are kind of three things that I really want to make sure that we cover with this show, and that is first, the science of, well, kind of the data aspect of how important it is for us to be aware of other people and their differing backgrounds and you know, just being empathetic of others. And then to convince us all that we can actually make a difference and improve other's lives and our own so that, like there are actually things we can do. And finally, to give practical tips and ideas of things like specific things that we can do to improve our community and help be more inclusive in that way.

    Just to kind of get our conversation going, what are some data points around, like the different people in the tech space? Like why, I'm having a really hard time starting out this question, (laughs) but yeah, what are the different, like people in tech? Like why do we care about these different people in tech?

    OMOJU: I guess I'll go for it. So the demographic landscape right now is pretty much, I think it's around 20 or 15% are historically underrepresented people. And those include women, people of color, persons with disabilities. And so basically a majority of the technical workforce is white and Asian male, so we have that demographic well represented, but everybody else is underrepresented. And everybody else is around 70% of the American population. So just from a workforce development perspective, it doesn't make sense to leave out almost 70% of the population, especially when there are so many technical jobs that go unfilled in the United States. So just from an economic perspective, you just have to solve that problem. And so that's who's there right now. And actually, that's not who's there right now, those are who graduate as technical people. Whether they go on to be there is another whole question. And when they do go on to be there, often within three to five years, they decide they are frustrated, and they leave the technical profession. So it's like a leaky pipeline.

    KATE: I can speak from the game sector. We at the IGDA, we do an annual survey we call the Developer's Satisfaction Survey, and our demographics break down in the gaming sector to about 20% women, and as far as people of color, it's vastly dominated by Caucasians at the moment. 76% of the people report that they are Caucasian descent. And so, yeah, the game industry has been, I guess, pretty well-known to be mostly white, mostly male, and that's been an issue for a long time, now. But when you look at the consumer demographic, like the figures from the ESA, in the US, the number of women playing games, it's almost parody with men, it's close to 50-50. Women are about 45% of the game playing population. And people of color are again, much higher than the people in the actual workforce. And so I know on our side, we're definitely looking at a situation where the workforce does not represent those who are actually consuming the products that are being produced by that industry. And so our basic goal in that case is essentially, we want to see that those that play games, or those who make games better represent those who play games.

    STEVE: From a disability perspective, for Autism, specifically, the current estimates are about 80 to some say as high as 90% unemployment or underemployment for Autistic individuals. Some of the highest unemployment rates for any "disability". And so, but I've talked to people who are paralyzed, people who have non-union fractures in their legs, which means the bone didn't grow back together correctly, and mobility is limited, and they're super talented folks, but they can't find work.

    KENT: I think that, Steve, you kind of touched on part of where I wanted to go next was, and this sounds awful, and like, I don't mean anything bad by this, but my next question is why should we care? Why do we care that there are underrepresented groups? And obviously, I do care, but I think that's an important question that some people may have. What makes the difference whether these different groups are represented well in the tech industry?

    STEVE: I think it's, you know, the same reason as it is for disabilities as it is for gender and race and any other segment of the population is everybody brings a different mindset, everybody brings different capabilities, everybody brings... and ultimately, if all lives are equal, everyone has value, and why not be inclusive of everyone?

    KATE: Well, you know, I think from a creative perspective, in the game industry, one of the biggest phenomenons over the last several years has been the rise of Indie game development, mainly because the tools for creating games have become really cheap or they're free, and that has democratized game development in a way that we've never seen before. So basically, almost anyone who has even the interest in creating a game can do so by just getting the tools and downloading it if they've got the technology, they've got the computing technology, they can start making games. And so a lot of the resurgence we've seen in the game sector recently, while we still have major blockbusters, just like the film industry does, like, you know, you've got your Grand Theft Autos, and Call of Duty and Halos and all that stuff, but the real interest in the game industry, sort of a renaissance has come from Indie games, and a lot of these Indie games are being produced by people who don't represent the typical demographic of the game industry. We're seeing a lot more women and a lot more people of color creating games and bringing their perspectives.

    And so, to the point where it's changed the industry. So like, with the last console launches, with the PS4 and the Xbox One, you know, Microsoft and Sony were bending over backwards to create a platform so Indies could publish on those consoles. And the reason they did that, from my perspective, is that the companies realized that the innovations in content and the innovation in games are coming from the Indie game sector, which is a lot more diverse than those who are actually creating the big AAA games. We're gonna continue to see this as time moves forward. I think it's really exciting to see. And what it's showing is that having this much greater diversity and voices creating games because games are an art form, we're actually seeing the game sector kind of have a resurgence, and renewed interest as well as a greater reach to a lot more people.

    KYLE: So I had a question. The statistics that were quoted just a little while ago about, you know, 20% identify as women and 80% identify as men and that sort of thing. And particularly, the racial demographic statistics, like how many people identify as Caucasian and that sort of thing. How much of that is centric to the United States, versus, or incorporating all of the world? Because I, for example, have trouble, just my own personal mindset, I have trouble believing that if we incorporated the billion people in India that use the Internet, but maybe use a more little, like feature phones, if we incorporate all the people in South America, all the people in China and all the other parts of the world, I have trouble believing that the usage of the web really is so heavily skewed towards Caucasians. And I don't mean that to say I'm somehow a minority, but I'm wondering how inclusive are we actually being in that statistics gathering. And does is that too big of a chunk to bite off, or should we be thinking about it in that bigger global sense?

    OMOJU: So I can take this one. From a global perspective, the racial demographics, they change, but one thing that is almost to the point of being a cultural universal is the gender demographics. So for example, if you go to the African continent, sub-Saharan Africa, so I've done this analysis just to understand, like I used to be at Google.org, and this was part of my position. I was the Computer Science Education specialist. So thinking about this from a global perspective, let's say we wanted to solve this problem for the entire world. And let's say that you want to actually pick people that look like me, which are women of African descent, there are three major places you go to. You go to the United States, 30 something million people. You go to Brazil, 40 something million. Then go to sub-Saharan Africa. All those places, women are vastly underrepresented in technical professions, in the professional side, as well as on the education side. So you will have men writing code, you still won't have any women doing any of this stuff. And those places, half the population of those places are also female.

    The same thing we see in China. India is slightly different, you see more women in India. However, once they cross over into industry, they get stuck at a lower level. And by the time you get up to mid-management in technical professions in software engineering, all the women are gone. They've gone to the business side of the company. So now you have your VP of marketing, VP of sales, they can be women, you know. But somehow, still in engineering ladder, they've still disappeared. And India is pretty much the light of the world when it comes to advancement of gender equity in technical professions and they still have challenges getting women up the ladder in engineering. So it's almost like there's nowhere in the world really solving this right, except for a few middle eastern countries, whose culture actually helps this problem better because they set up systems where women and men, they don't work in the same environment, so therefore, they've done remote employment very, very well. And as a result, women can advance further because they never have to go to work and be in the presence of men. They work from their houses and from their centers. And so, very few countries, though, they're just very small specs. Beyond that, in places where men and women freely interact, those problems persist.

    BRIAN: I was curious if, see, you kind of hinted on a possible solution there, but do you have ideas about, you know, top causes of, you know, the reasons for these statistics, and you know, the underrepresentation, you know, just basically the root causes that you think are most important?

    OMOJU: I mean, this is not even rocket science. It's just very simple things, as simple as everybody, you know, you grow up, you're a little girl, and you want to climb a tree, and people say girls shouldn't climb trees because they wear dresses. It's un-ladylike. So it's just silly cultural things, and that kind of carries over into mathematics. And people have, like a math phobia, even though computer science or writing code is not that math heavy. And so those kinds of small little things just sort of persist. And most people, most humans, the strongest urge is the urge of belonging. They want to feel like they belong wherever they are. So for a lot of people, you have to be one of the first few to really break through. And for most people, they don't want to spend most of their life being an extreme minority. It's like, why? And the people who want to do this often have the technical and intellectual acumen that they can easily switch to other professions and crush it. So it's kind of hard. It's like, you're smart enough to do anything, you can still make just as much money and not be underrepresented. Most people are gonna be like, "I'm gonna leave." So that's the hard problem we actually have to solve.

    KYLE: So there's lots of different societal--

    BRIAN: I think Kate's, Kate's talking but was muted.

    KYLE: Okay.

    BRIAN: (laughs) Just mentioning because I see her mouth move.

    KENT: Kate, there's a hot key command to your control key to mute and unmute yourself.

    KATE: Yes, for some reason it muted itself, so sorry about that. Yeah, I mean, just to add to that, one of the big challenges we have, I mean, we know from the tech sector, from the history of the tech sector, that it's predominately male because it came out of you know, hard, computing science way back in the '50s and '60s. And that was a very male dominated field, even though a lot of early code, and a lot of, there were a lot of innovations that were done by women who were working in the computing science sector at the time. But it's just historically, it just remained a very male dominated space. One of the problems we're seeing, like on the game side, for instance, is that we see young women like in elementary school, like girls are extremely excited about STEM subjects and they grasp it really easily, they get super excited about it, and we see this amazing precipitous drop-off in middle school and junior high.

    And it's almost a universal phenomenon across the board, not just in North America, but globally. And a lot of it is due to, you know, hitting puberty, there's a lot of social pressures. And like was stated, there's a lot of cultural pressure that gets added when a young woman is starting to grow up and decide what she wants to do. A lot of times, either the cultural reasons or just social pressure, it's like, "No. Don't be a geek. Don't be a nerd. That's not a cool thing to be. Go do this instead." And so one of the big challenges we're seeing is that in that age range, in that middle school age range, we see that drop-off. Because then those who actually "survive" it into high school and into college, they maintain an extreme interest and go on to pursue engineering and technical fields. But trying to stop that huge drop-off has been a major, major problem.

    KYLE: So, society has got, has made suggestions for a lot of different solutions to these structural bias problems that I think all of us here fully admit exist and a lot of people listening probably admit exist. So we don't need to prove that they exist, but there's a lot of different thoughts on what is the appropriate response to an observation that these things exist. And I would like to actually discuss, more concretely, the gap that may exist between those that believe that if we see that there's a problem with gender in tech, or there's a problem with racial diversity in tech or other things like that, that to fix those problems, we have to, those of us that care about it, have to actually go out of our way to increase, you know... I'm thinking in terms of like when a conference organizer is trying to have a diverse conference, so they actually have to go out of their way to invite people of color, people of different gender persuasions and all of those things, because it's not just enough to have an open field and say, "Everybody, come join me if you want," because the structural problems prevent those people from coming in the first place. So there's that side.

    And then, there's the other side that says technology ought to be a meritocracy, and everybody's free and we're blind to the issues of race and gender, and the best ideas win. There's a huge gap between those two fields. And I sense that that is one of the biggest reasons why people hate the word diversity and they hate the word inclusiveness. And they feel put off by those terms because they think when you talk about diversity and inclusiveness, you're saying you have to be in one of these two camps. So how do we deal with those two fundamental, and maybe there's more than that, maybe it's more modal than that, but how do we deal with those two fundamental camps of how to solve this problem?

    STEVE: I don't think it's, for the second camp, it's not possible to just be a free for all meritocracy. We all have our own inherent biases, and we all have our own privilege. And the crazy thing about privilege is when you have it, you don't see it. And so, I am a white male. And I've just been learning in these last few years about the privileges that I have that those who are not white or those who are not male may not have. At the same time, I'm learning about, in my story, I was diagnosed with Asperger's about four years ago. So I'm on the Autism spectrum and I've been learning about ways that I may not have privilege compared to others. And so we all have inherent privileges and disprivileges that form a bias in our minds that make it difficult to say we're gonna turn a blind eye, and we're gonna have a meritocracy, and we're gonna be fair.

    KYLE: Isn't that one of the cases where... and I'm trying to make sure that both sides here are represented, isn't that one of the cases where somebody would argue that if the level playing ground meritocracy thing isn't working, it's because we're not focusing enough on turning a blind eye to those differences and letting people come in as they see fit. Isn't it really just, we have to do that more? Or why isn't it not that we have to do more, and we have to have an entirely different strategy? Like for example, you know, society has had Affirmative Action, for example, which is creating laws specifically to go outside of the normal fairness realm and try to tip the balance back. So does tech need to mirror what society has done? Or can tech simply say, "We just need to get more and more pure, more and more meritocracy?"

    KATE: One of the things that I would mention is that it's been evident in the last couple of years that one of the big issues in the tech sector is unconscious bias, and we've seen Google and Facebook and other companies be very overt about creating training around unconscious bias within their companies because they realize that, you know, and this is the situation, I was at Microsoft for 13 years, and I saw this happen quite frequently, is that like Steve mentioned, I mean, we do all have inherent biases, and a lot of times, we don't recognize them, we just can't see them. And so I know in the hiring process, for example, a lot of time you'll get hiring managers who, as people, they may not be overtly biased or have any, you know major concerns about any race or gender or anything, it's just that it's a human propensity to hire people or to have people around you who are like you. Or, if you have a team that, for example, is mostly guys, then there... and I've heard this more than once, where a hiring manager will say, "Well, I'd like to hire a woman on the team but I'm afraid that she won't be a good fit and she might be disruptive to the team." Which is, part of that is ignorance because there's been sociological studies that show in that situation, you add a woman to a group of men, and actually their performance improves because it kicks in this natural anthropological competition around her, you know. So that's kind of a misperception. But I think a lot of these companies are realizing that they need to address unconscious bias as one of the issues that they're facing where they just need people to be more aware of making conscious choices between qualified candidates and not just going for that default of hiring someone like themselves.

    STEVE: Yeah, I think for unconscious bias, I read a story, an article recently about black children in the education system and how they are more likely to be given, to be expelled or to be given detention versus white children because they found an inherent bias to view them as older than their age. And so, we all kind of have these inherent biases in our head. From the disability perspective, especially from, it's easy when you see someone in a wheelchair or someone with a cane to see, "Oh, they need some assistance. Let's help them out." But there's an unconscious bias... and we'll talk about Autism for a sec, if someone comes into an interview and they're very monotone, even more than me, and they perseverate and they don't make eye contact, there's a social bias as well. People talk about team fit, and that person may be an excellent programmer, but because of the social stigma, the social bias, they're not gonna get the job.

    KYLE: So beyond just feeling an ethic like we should fix these problems because I deeply feel that ethic. I have taken actionable steps in my career to try to speak out on this topic, so I'm not one of those that needs to be convinced from a morals perspective that we should be working to try to address the problems, but this is a podcast about the data behind it. So is there any data that lets us know the efforts to, you know, as those two camps that I talked about just a moment ago, the camp that says, "we need to go above and beyond," versus the camp that says, "no, we just need to be pure and level playing field." For the first of those two, is there any evidence that efforts in those areas have actually made a difference? Or are they just looking good PR-wise, but they aren't actually moving the bar forward?

    OMOJU: Yeah, so let me, part of the research I actually did for my PhD was studying this phenomenon from the data perspective, as well as the psychological perspective, as well as the social perspective, so we can have it all together and actually know what is actually going on. The interesting thing that I found in the research that I did not even know existed was majority of the students of color, especially African-American students I spoke to, at the undergraduate level in computer science, majority, over 80 or 90% of them had participated in some summer program for wannabe engineers when they were in high school or something. It just kept coming up over and over, and over and over again. It basically seemed, I hardly met a student that had not participated in that kind of a program. So that shows that those programs, they do bear fruit ahead in the future, but the issue is, you need to do a longitudinal study to figure out the efficacy of things like that. So you came up with a program in 1985 or 1990, you got to wait until like year 2000 or something or beyond to see what's happening with the students in the program.

    And also, research around this kind of issue, especially around the issues of equity with respect to underrepresented persons is sort of new-ish. Historically, there hasn't been a lot of data. If you dig into the research and say, "I want to learn about the experiences of African-American women in computer science," the number of research is so low that you can't even pull from it. So even the area itself is under-researched. So it just becomes a compounding issue. There are not enough researchers researching it because everybody that was already doing research did not finish that demographic. And so it wasn't a problem that their brain said they should wonder about, so there's not enough research in the area to begin with as well. But there is enough research around issues of gender. And it has shown, over and over and over again, there are tons of research, especially from Harvard Business Review and Harvard Business School, of the impact of women in teams and how those teams often over perform versus other teams. And more interesting with respect to Silicon Valley and venture funding, companies that were venture funded that had women as part of the founding team often perform better for their investors. So like, it's just pretty much from an investment perspective, if you are part of an investment team, or you are VC and you are funding things, and there are no women on the teams, you are basically going against your own interest. If you want to make money, make sure that there's at least one or two women in each team that you're funding. And you can actually track the data and run analysis and see that outcomes are better in your favor when women are on those teams, especially when it comes to things that have to do with money.

    KENT: That's actually kind of interesting to me. So is it the fact that, like, I guess this is more of a question of, like are women just more capable? Or is it better to like is the reason that they're so successful because they have more perspectives and more diversity in the team? Is that what makes it successful or is there something, like inherent about, like if it was a solely, only women team, would that perform better than an only men team? Or is it more about diversity in the team?

    KATE: Just a couple of quick comments on that, I mean, one thing is that there is a VC here in the Seattle area who came out, I believe late last year and he said that going forward, he's only going to fund women run companies. And the reason he said that is it's the women run companies who actually come through and do exactly what they say they're gonna do. And he said a lot of the male run companies, they don't always deliver. Sometimes they use a lot of BS, say, "No, everything's fine, everything's fine," whereas he found that the women are much more honest about where they are with their business strategy and with their progress. And so he just openly declared that from moving forward this is how I'm gonna spend my money. And that was kind of a bombshell. A lot of people were like, wow, that's kind of big news that he would make that kind of overt decision. But he's saying, "Look, it's just purely about results. I get results from women run companies."

    Now, I personally think that some of the factors that feed that is that women, a lot of women especially who are in this sector are we realize what the challenges are, and a lot of them have fought their way to get in this sector and have stayed in this sector despite a lot of challenges, whether it's open harassment or unconscious bias, or whatever it might be. And what I find with a lot of my friends in the tech sector, there is a certain, kind of inherent tenacity that comes with wanting to succeed that may not be as quite inherent in a lot of men who are in the sector. And it's true not just women, but also people of color because the barrier has been there, and the perception that it's been a lot harder for them to get ahead, to get the position they want and everything, there is a drive that I think is pretty unique to people in that situation. And you see that it's not just about gender and ethnicity, either. I've seen that a lot in people from emerging markets for example, who want to rise above their economic situation, there's a level of drive there that you generally don't see in developed countries where people have it "easier."

    KYLE: I think we can probably all agree that the constituency that is served by the tech industry, meaning just about the entire world's population is, by definition, incredibly diverse. And we can also admit that it's a really tiny percentage of us that are actually participating in the building of the stuff that the rest of the world consumes. So it stands to reason that the more diverse those teams are, the better they can address those concerns. But beyond reason, what data lets me know, for example, that if I build a team that has somebody with disability challenges on it, that my team is going to be better able to serve that part of the demographic? And if I have a team that has someone of color or, you know, multiple people, I don't mean like token, I mean multiple people of all of these different groups, that my team will be better able to serve it? Beyond just, like intuition, what data tells us that?

    OMOJU: So your team, for example, if you had a team and you had persons of color, it is not the case that automatically they'll be able to solve problems and attract customers who look like them. That is not necessarily true. What happens is, it's the diversity of points of view that creates a product that speaks to more people. So we've seen the same exact kinds of things actually happen in technical curriculum that is culturally relevant. So for example, you're trying to do like a data science module on rap or something like that, the idea, most people would think, "Oh, the black kids will love it." Not necessarily the case, not necessarily true. What that does is, basically gives everybody permission to be more creative and to start looking at the same material from more perspectives. And what you get with that is a richer, better product that reaches out to way more people. And that's what you just keep on getting. And overall, you keep building better, better products. And better products talk to way more people. Black people don't necessarily have like special black people problems. They have the same kinds of problems that most people have. But if you design a product in a way that allows for multiple perspectives, you will attract multiple kinds of customers.

    KYLE: So if I went and built a team that had a white dude from every single continent, and now my team has "diversity" because now I have people from wildly different cultures, wildly different backgrounds, speaking very different languages and all, will naturally out of that group arise the awareness to understand issues that perhaps would include the women's perspective and racially diverse... I mean, will it just come because I had a bunch of different kinds of white dudes? Or don't we need more than that?

    KATE: You need more than that because, I mean, if you still have white dudes from all over the world, how are they gonna have the women's perspective, for example? Or how are they gonna have the sub-Saharan perspective? You know, you do need more than that. And I actually need to leave in a second, so I wanted to put out this one last comment. So last year, we had IGDA hosted what we call our Leadership Summit, and our keynote speaker was Kristina Reed. And Kristina was a producer at Disney, and she's won three Oscars. She was a producer on Big Hero 6 and the shorts Paperman and Feast. And she gave this fantastic talk about what inclusion means in the creative space and in the creative process. The most interesting part about her talk was that she did not address racial diversity, she didn't address gender diversity, she didn't explicitly address diversity as we know it. What she was talking about with inclusion is the inclusiveness of thought and inclusiveness of opinion.

    And so what she outlined, and what she, and you know, this is, yeah, it's not hard empirical data but it's qualitative data that resulted in three Oscars, so the highest accolade for her field. In every one of the projects that she worked on as a producer, they took the approach that every single voice mattered. Every single voice in their office mattered. It didn't matter if you're the janitor, if you're the receptionist, whoever you are, she said when they did idea sessions, they brought every single person into the room and encouraged everyone to speak up, and made it clear to them that this is an absolute level playing field in this room, and every idea and every piece of feedback matters. Now, obviously the creative leadership team on those projects, it was their job to then parse which ideas where actually gonna be, you know, applicable to the project or not. But it was really interesting that she outlined this approach about inclusion in the most broadest context, and that resulted in enormous success for them. So basically, the message there was that the more diversity you have in that room, the better your inclusion is going to be and the more likelihood you're gonna get voices and opinions that you just never would have considered.

    BRIAN: That's a really great action item. Maybe we should shift into some of those. I know you have to leave soon, is there any other action items that you can give us to, you know, advocate and help? I have the most amount of guilt. I'm the most privileged white dude in the world, so I need to do things to help out. And you know, I always see tidbits on Twitter and stuff, but what do you feel is the most important things I can do on a day to day basis?

    KATE: I think part of it is just pure awareness. And I know that's kind of cheesy to say, but honestly, in my experience, it's the number one thing. It's like, it's more than half the battle, is just making people aware of their own behavior. It's like in my culturalization work, that's exactly what I do for companies. I help them find political and cultural sensitivities in their content, so they're not gonna get in trouble, like have their product banned by a government or have consumers uprising against them. A lot of that is just being aware of the choices that they're making. So a lot of times, it takes someone, whether it's that individual or someone around that individual, who just simply asks the question, "Why is this company hiring nothing but white dudes? Why are we not looking at other candidates?" And a lot of times, you'll hear hiring managers say, "Well, I can't find the candidates. I want to hire people of diversity but I can't find them." And so, you kind of have to go down the rabbit hole and investigate, okay, so how do we find them? Don't just end it there and say, "Sorry, you know, that's the way it is," which I see a lot of companies do, but actually take the next step and say, "We want to find candidates that we can consider that are not just the typical demographics." You have to keep pursuing it, and not let it go.

    I think that, to me, speaks to companies making it a value and individuals making it a value that, you know what, being inclusive in that most broadest sense and trying to get as many voices in the room as possible is our goal because we believe it's ultimately gonna make our product better, which therefore means we're going to increase our revenue, which ultimately, that's the argument that you have to make with a lot of these companies is that you are broadening the appeal of what you are creating and broadening the perspectives that are feeding the creation of it. And therefore there's argument to be made that it can increase the bottom line, which that, for better or worse, is usually the only thing a lot of companies are gonna listen to, but it works. I guess I would just say having an overall consciousness of what they're doing and the actions they're taking is really critical. And with that, I'm gonna have to say goodbye.

    KENT: Thanks for coming, Kate.

    KATE: All right, thanks very much for inviting me.

    KENT: Yep, so I would like to continue on this train of practical tips that people can do. And if anybody watching live has any questions about anything that they could do, or suggestions even, I guess, just tweet the hashtag #JsAirQuestion and in a couple minutes, we'll go ahead and answer those. For our guests, do you have any other suggestions of things that we can do, practical tips to help improve the diversity in our communities?

    OMOJU: I think one simple one is, since most of us are on Twitter follow people who are not like you. It can be hard sometimes, especially if you have, like differing political views, you might find yourself getting slightly infuriated and worked up, but you got to remember that these are human beings as well, there's a reason why they think the way that they do. With more technology and more freedom over the content we consume, many of us have rolled ourselves into a bubble where we only hear from the echo chamber. So follow people who are not like you, and see if you are, someone like me who's a black woman, that means that I'm following persons who are, like Asian men, and white men, I mean, all kinds of different people, transwomen, just listen to that kind of conversation, and it helps you broaden your perspective of what their experience is like, so when that opportunity comes that you're building your team or you're mentoring people, you are no longer just mentoring people who look like you, you are mentoring a diverse population of persons. That's just an easy tip.

    KYLE: I, to build off of that same thing. I just wanted to share with the audience something that I've done personally. So for those who don't know, I've been on the conference speaking circuit for quite a while, and seen a lot of different things in a lot of different places. It was fun, but at the most recent Fluent conference, I was privileged enough to give a keynote and in that keynote, I essentially announced that I was stepping down from conference speaking specifically because I go to all of these conferences all over the world and I see a lot of the same people that look like me and think like me giving all the talks. And I don't see enough of that, and it's too hard, and I do a Google search, and I try to find different perspectives on a piece of tech, all I find are white dudes writing about it. I don't find other people. So specifically in the area of conference speaking, I decided to step away from conference speaking to make room for different voices. But it's not just enough for me to make a gap. I have to try to help fill that gap, so I'm actively looking for ways to try to encourage and mentor other people to step up, and hopefully inspire other voices to be in those slots. So whatever position you find yourself in, whether you're a conference speaker or you're a writer or whatever, you should be looking for ways to lessen yourself so that there's room and you can encourage other people to take that step up as well.

    KENT: Yeah, that's a great tip. Steve, did you have any tips or ideas of how we can improve our community in this way?

    STEVE: I think while we're talking about diversity, the overarching goal of our area I'm focused on is neuro-diversity. And sometimes, it can be more subtle than other types of diversity because someone may appear to be neuro-typical, they may appear to be... so I think awareness is good, but we also need understanding. We need to understand the individual challenges. And that's where, and this is controversial, but I step away from team first principles. And as was mentioned earlier, instead of talking about equality, equity is more important. What does each person need to be successful that may be different from what other people need to be successful? For people in the spectrum, that may be a dark, quiet corner. It may be clear and written instructions. It may be other combinations like those that then help them utilize high intelligence and attention to detail, intense focus, creative, out of the box problem solving skills, you know, things we should be hiring for in tech.

    KENT: Interesting, so you're suggesting, you know, maybe the 9-5 workday doesn't work great for everybody. Let's make it more accessible to, like regardless of what time of day works for you, and then also like, maybe some people are a lot, can focus a lot better when they're working from home, and so let's be more remote friendly, stuff like that?

    STEVE: Yeah, our entire company works remote, and for those reasons, sensory issues, social, political. And frankly, we by and large don't have set schedules. So I can often get more done between like 11pm and 5am than I can from 5am to 11pm (laughs) and lots of folks are like that. Why not let them do their best work? If you get your stuff done, I'm happy.

    KENT: Totally, I think that's good. I just started working from home and I totally love it, so I'm all over that. Cool, is there anything else, because like Brian, I am insanely privileged, and I want to know more things. We were talking a little bit about, Kyle brought up conferences and how they, lots of times they have to go above and beyond to reach out to specific people and invite them to come. Is there anything else that, maybe a conference or a meetups organizer could do to improve the inclusiveness of their event?

    STEVE: I think along with what Omoju said about getting involved with other, you know, following more diverse people on Twitter is, get involved in more diverse communities out in the real world. We tend to, as was said earlier, we tend to self-select, it's kind of our human nature, self-select for people who are like us, so go out and get involved in various diverse communities, whether it's gender or race or disability or whatnot, and get some different perspectives, meet some new people. A lot of times, there may not be a great intersection between our communities.

    OMOJU: Another thing I would add to that is to actually be an onboarding ambassador. So you might decide, "This year, 2016, I'm gonna focus on two persons and I'm gonna be their sponsor." So one of the things you can do is, if you participate in open source software, you can decide I'm gonna spend this year trying to onboard one or two people into an open source project, and make sure that the pull request gets accepted. So you are basically grafting them into the community. It's a lot easier to do that than to, like go big over the conference schedule because what you're doing is, you're becoming that ambassador that is actually welcoming people, and actually showing them real things they can actually do. If you get a pull request accepted, that sweet joy of success is enough to make people stay. And once you've mirrored that behavior, they go and do the same thing for other people, and that's actually how you change things. It's not some big magical thing in the sky, it's just one or two people. And one or two people over a year is something that you can do without getting mentally fatigued.

    KENT: Wow, that was awesome! That's a fantastic bit of advice, and definitely something that I could, like really practical for me. And I'm a huge advocate for being welcoming and inclusive in open source, so great, yeah, thank you for that. We're coming down on our time, so before we... we don't have any questions on Twitter, so we do have a little more time, but before we get into our tips and picks, is there anything else that anybody would like to bring up before we--

    BRIAN: I would, really quickly, just wanted to make one comment. You mentioned Omoju, that people don't like to be, you know, in a place where they're the minority and it's not really comfortable. But as we make these efforts, it's kind of, we have to get over that initial hump. And I don't know if you have any tips or ideas about how to maybe, initially attack that issue to get a few people so they don't feel so underrepresented and out of place.

    OMOJU: So one of the things I actually advise people to do if you're in a position of, you know, hiring manager, or even at universities looking to hire professors, instead of hiring one person, why not just wait, get your recs together and hire four or five at a time. So immediately you bring in, like a set of small critical mass, so you don't hire just one woman. Like, that's one of the worst things to do, because then she becomes the Barbie engineer. She'll just become the female engineer. She's no longer an engineer, she's like representing all women. But if you hired five female engineers at the same time, they're now engineers. And so, that might be very hard to do in big companies, but smaller companies, especially if you have room, if you have enough power over your team, bringing in things together, three, four, five at a time is a lot easier for the sense of belonging than one person who happens to be the only person there for five years. Like, you're asking that person to do a lot. And they're fighting so many demons in their head, you're actually not getting the best production from them, so it doesn't even make sense for you as well. You want to bring someone in, and you want them to be in an environment where they can do their best job. You don't want them to come in there and start to, like fight some kind of civil rights battle. That's not what this is about.

    BRIAN: Right on.

    KYLE: I just wanted to share one other thought that occurred to me while listening to these other fantastically smart guests here. Again, building off of this notion of hiring, I believe very strongly, I think a lot of other people would agree, I believe very strongly that we, one of the things that holds us back is that we haven't fully admitted, as an industry, that the stuff that we do is not about code, it's actually about people. And that means that hiring needs to be more balanced in figuring out what we're looking for. We use these umbrella terms like "good culture fit." As a matter of fact, maybe you ought to find somebody that's not a good culture fit so that you can get a more broad culture. But at the same time, we don't actually have to say, "I have to have a single member of my team that represents every possible different view or there's no way for me to be diverse." What I think we need to look for is people that demonstrate, with their actions, that they are empathetic people. Even if they don't know a thing or don't personally have experience with a particular perspective, there are people that can be big enough to go outside of themselves to try to look for other sorts of input, and those are the kinds of people that we ought to be trying to hire more instead of just a guy who can write the algorithm fastest on the white board.

    KENT: Wow, yeah, that was great. And that's really challenging the status quo of like, "Well, we want to have people who fit our culture." I actually really like the idea of, "No, we want people who are gonna broaden our culture, make our culture more, like be able to have more people fit it." So that was great. I think we're gonna have to wrap things up. So thank you to our guests for coming on. Let's move into our tips and picks, and then we'll just wrap things up. We'll have panelists and me go first, and then we'll let our guests get into their tips and anything else they'd like to bring up as well. Brian, why don't we have you go first?

    BRIAN: Sure, I wish I had good tips and links that had to do with the show. I learned a lot today, and always have an open mind to things I can do to help. I threw just a few picks on here that there's PureScript miniconf coming up to check out. That's in Catalina Islands. And then I've been reading this Algebra Ch 0 book, which is really interesting. And I watched a great talk on, I guess, just programming architecture from Zach Tellman, that kind of talks about just metaphors the whole time, but it's really eye opening and mind expanding, so check it out.

    KENT: Cool. Kyle?

    KYLE: Yeah, couple of quick things. I have one tip, and it may sound a little bit out of left field or out of context, but those who follow me know, so my tip is write your code, every once in a while, maybe not all the time, but write your code as if it was intended for kids to read and learn. I've actually been doing this specifically because this weekend, I'm giving a workshop at OSCON kids day, so I'm going to be teaching a group of six through 12 year olds how to write JavaScript to make a game. And I've been intentionally trying to write my code so that it will be easier to help kids understand. And it's continued to broaden my perspective on what it actually means to have code readability. So I think it's a good exercise for everyone to kind of push outside of their normal thought process of like, optimizing for, you know, senior developers.

    A couple of picks for you. First is a resource that I actually found to be fantastic to pass out to people. I've already sent this link out several times now, simplified JavaScript jargon. A big long list of all the different acronyms and terms that we throw around, especially in the web world, and in JavaScript particularly. It's a nice little quick synopsis of each of those ideas to help somebody kind of get their brains into the right context.

    Another one, which I have been working on also as part of that game for kids day, I've been, one of the games I'm working on is Tic-Tac-Toe and I learned about the algorithm, an AI algorithm for having the computer play you in Tic-Tac-Toe, and it's called the Minimax Algorithm. So I thought that was an interesting algorithm, and I got to implement that.

    And finally, my employer, MakerSquare, I'm head of curriculum for them, we are opening up a New York City campus here in two weeks and so I'm super excited about that. If anybody listening is interested in tech schools that take learning deeply and seriously, check us out.

    KENT: Great. So I'll go next and because Kate took off, or she had to take off early, I'll give her tip that she left for us. So, for me, my tip, this is like, not even a novel idea or anything, but it's something that I've been doing recently is using reminders. So Google Inbox has reminders that integrates really well with, like Calendar and stuff like that. And so I don't have to keep things in my head. I just put it in a reminder and I forget about it, and it's just really, really nice. And Google Inbox, or I guess it's called Inbox by Gmail, but it's got a really nice system for that. So I recommend that as a tip.

    For my picks, I just ordered a shirt that says, "You can sit with us" on it. I was inspired by Brad Green at his Fluent Conf and ngConf conf talks. And so I've got a link where you can get your own. I think you have two weeks before they stop printing it, and so check that out.

    And then a really exciting tip, Irwin Datin, I think is how you say his name, I've got a link to his story here. He, a couple weeks, or like a week or two ago, filed a pull request on the JavaScriptAir.com website that added deploying the JSON data for the show information and stuff, and I was like, "Well, that's kind of cool, "I wonder what he wants that for." And he said, "Believe me, you're gonna love it." So he just told me this morning that he created a JSAir app, so a native app made with React Native for iOS and Android. And so the repo for the app is open source, so if you're interested in React Native, go check that out. And then download the app, it's pretty cool.

    And then, finally, my last pick is a talk by Joe Eames at Angular Connect, and it's called Becoming Betazoid, How to Listen and Empathize with Others in the Workplace. I think that's really applicable, and it was a fantastic talk, so check that out.

    For Kate, she has a couple of links here that we'll have in the show notes, but her tip is "be aware that you and everyone has natural bias." I agree with her, I think that awareness is a big part of this picture. I don't think anybody really intends on being a non-inclusive, unkind person. I hope that nobody would intentionally do that. I think a lot of the battle for those of us who aren't intending to be biased is just the fact that bias is really natural, and we just have this unconscious bias. So I totally agree with Kate on that tip. And I would recommend you check out her links in the show notes later for some more information about that. Okay, Omoju, why don't you go next?

    OMOJU: So my tip is always ask why, and never lose your curiosity, especially if you're doing something, like I do, with data science. At some point, you can dig into a problem to the point that you just want to find, you just want to make sure that your evaluation metric is just perfect, you want to increase the precision to just extra, to the point that you've actually lost focus on what the problem is. You always want to keep that perspective and ask, "Why am I doing this? Why am I over-optimizing this? Why? Why, why, why?" Never stop asking why.

    And my picks is four different picks. The first one is this great TED talk that I love so much and I think everybody should listen to at least once a year, it's called Danger of a Single Story. It's by the Nigerian writer, Chimamanda Ngozi Adichie, and the link is here. Another one is a newsletter called Tomorrow Looks Bright. That newsletter focuses on African-American, women of African descent and their creative artifacts, so the companies that they've built, the products that they've invented. It's very interesting, and it's very cute.

    The next one is a podcast called Call Your Girlfriend for long distance besties everywhere. It's fun, it's by And it's like a feminist podcast, but it's just so fun. It's fun, it's like laughs. And the last one is Recode Decode by Kara Swisher. I love her perspective on tech and the kinds of people that she brings in. One of my favorite episodes of Recode Decode was when she had a conversation with Anne Wojcicki of 23 and Me and talking about building a science company and dealing with the FDA and fighting regulation and helping to create that public, private partnership and founding this company and persisting over the years with awesome borderline science, bringing that to the masses. So those are my picks.

    KENT: Great. Yeah, we love podcasts here, so thanks for those recommendations. Steve?

    STEVE: Oh, I'm still trying to figure out how this works, but, I'll say that we are, at Platinum Bay, we are actively looking for folks on the spectrum who are in software. And we are looking for AngularJS folks specifically, along with a lot of other things. So people in your audience, feel free to reach out to us.

    KENT: Cool, I put that down as a tip for you, "Platinum Bay is hiring." (laughs) All right, great, this has been a great show. I think that, yeah, we can definitely do more things. I actually just thought of a tip, if I can be so pretentious as to suggest a tip for somebody as privileged as myself, for ways that we can become more inclusive. And I just wanted to mention, so one thing to combat the natural or unconscious bias that I try to do is on the JavaScript Air website, when I was adding the functionality for having the guest avatars on the shows, I thought, "Okay, well, I don't want to have to worry about ordering these in any particular order." I think my first thought was, "Well, who should I put on first? Like maybe the person who's most influential in the space or something like that." And then I finally decided, I don't want to have to make any sort of judgment call on that because unconscious bias would probably direct me to do something, you know, that isn't right. And so, instead, I just said, okay, I'm gonna sort it by Twitter handle, so alphabetically, by Twitter handle. And so now I don't have to worry about it. And so there's no, like unconscious bias at play, even in the sorting of guests on the shows.

    I think things like that, we can really just like, just like Kate said, I wish that she was here because I want to give her like a high five, but I just think we need to be aware that we have unconscious bias, and that awareness will lead us, and that desire to avoid that, will lead us to question whether we're acting in a biased way, or whether we could, and prevent ourselves from even being able to act in that way. Really, it's all about just being inclusive and being good people to others.

    With that, I think we'll just wrap up the show with a couple closing announcements. A shout out to our silver sponsors, Auth0 and Trading Technologies, check them out. They're awesome for sponsoring the show. And then if you have suggestions for the show, go to suggest.javascriptair.com. And you can suggest topics or guests or both. And then if you have feedback for our shows, go to feedback.javascriptair.com. And if you'd like to sign up for our weekly newsletter, you can go to jsair.io/email. And then remember next week we're talking about transitioning from REST to GraphQL with Lee Byron and Nick, I can't pronounce his last name, but I will next week. (laughs) And then, as always, follow us on Twitter, Google Plus and Facebook to keep up with the latest.

    And one final announcement that I should probably mention, we do have openings for silver sponsors, so if anybody out there would like to have their company sponsor the show, that would be awesome. You get a shout out in the show at the end of the show, and also a feature on the newsletter on a rotation with the rest of the sponsors. Go to, let's see... I should probably have this on here, but if you just go to the website, in the sponsor section there's a button for becoming a sponsor that gives you more information about that. So that's our show, thank you so much Steve and Omoju and Kate for all coming.

    OMOJU: All right, thank you!

    KENT: We'll see ya.
  `,
}
